### PR TITLE
Code refactoring / job creation time and branch /  components specific branches

### PR DESCRIPTION
**Pull request by Guiiix**

### CODE REVIEW

**Comment by marmarek** [comment]
Can you make the time to use non-braking spaces (so it's either whole on the same line, or moved to the next line in full)? Currently depending on window width it looks weird sometimes:
image

**Comment by Guiiix** [comment]
Thanks for the reply. It's done.

**Comment by Guiiix** [comment]
This should be more readable now
image

**Comment by marmarek** [comment]
Nice :)

**Comment by marmarek** [comment]
There are two reasons why there can be no pipeline for given component+release - it wasn't run for it yet, or it isn't enabled for given release at all. The latter case is more common, and IMO displaying a lot of "unknown" only clutters the view. Can you skip those for no-pipeline case? But keep "unknown" if there is pipeline but specific job was not found (there are a few with no job for reproducibility for example). And in that case, it's probably fine to keep branch/date part (both will be "N/A" then) - it makes it easier to see why there is no info.

**Comment by Guiiix** [comment]
Okay, I added a "No pipeline found" instead :

image

**Review by marmarek — APPROVED** [review]

**Pull request merged**
